export const LOGIN_SUCCESSFULL = 'LOGIN_SUCCESSFULL';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = "LOGOUT"; 

export const FAILED_TO_CREATE_USER = "FAILED_TO_CREATE_USER";
export const USER_CREATED = "USER_CREATED";

export const LOADING = "LOADING";